spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  application:
    name: pret-open
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  datasource:
    name: test
    url: jdbc:mysql://121.36.22.92:3306/db_pret2?useUnicode=true&characterEncoding=UTF8&serverTimezone=GMT%2B8
    username: root
    password: AdMin@2019
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        tags: version=1.0,author=wujinsong
        healthCheckUrl: http://${spring.cloud.consul.host}:${server.port}/actuator/health
        healthCheckInterval: 10s
        instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
        health-check-critical-timeout: 600s
server:
  port: 8804
logging:
  path: ./logs/
  level:
    root: error
    org:
      springframework:
        boot:
          autoconfigure: ERROR

ribbon:
  eureka:
    enabled: true
  ReadTimeout: 600000
  ConnectTimeout: 600000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: false

hystrix:
  threadpool:
    default:
      coreSize: 500
      maxQueueSize: 500
      queueSizeRejectionThreshold: 500
  command:
    default:
      execution:
        timeout:
          enabled: false

qiniu:
  baseurl: http://oi42x1205.bkt.clouddn.com/

rong:
  cloud:
    key: p5tvi9dspex64
    secret: MtLrzuh321

wx:
  mp:
    configs:
      - appId: wx94af4a987003e14a
        secret: 41c30ad3020cd82a6ea67353f144abf6
        token: xpx
        aesKey: x5BIUL0nSaR77Wv3YYfR8Bvh5tqjiAuoI3PTKAIqoZE
  miniapp:
    configs:
      - appid: 323
        secret: 544
        token: 54354
        aesKey: 65655
        msgDataFormat: JSON
sender:
  name: \u5E2D\u4E39
  phone: 18916528900
  tel: 021-69898845
  province: \u4E0A\u6D77\u5E02
  city: \u4E0A\u6D77\u5E02
  area: \u5609\u5B9A\u533A
  address: \u4E0A\u6D77\u4E0A\u6D77\u5E02\u5609\u5B9A\u533A\u987A\u8FBE\u8DEF111\u5F0463\u53F7
  j_company: \u4E0A\u6D77\u6613\u7FBD\u6807\u8BC6\u7CFB\u7EDF\u6709\u9650\u516C\u53F8
  j_contact: \u5E2D\u4E39
  j_tel: 021-69898845
  custid: 0210036987
  clientCode: APBP_DAShow
  checkword: tjOl5JBdOb4TyaVunWo2YlQTspmUmVv3

sf:
  url: http://hda2-sit-ms.sf-express.com/manager/open/order/v2/createAndReturnDetail
  jcontact: '上海普利特'
  jtel: '13764488418'
  jaddress: '上海市青浦工业园区新业路558号'
  appSecret: 'SLYJBc83Xu5l2qRWZoNCzVzZpQbVDNP7H'
  appCode: 'PLT001'
  storeId: 'PLT001'



upload:
  baseurl: https://tms.pret.com.cn/
  path: C:\services\html\
u9:
  ulr: http://116.228.74.171/u9/