package com.pret.open.u9.warehouse;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.4
 * Mon Nov 05 09:33:35 CST 2012
 * Generated source version: 2.2.4
 * 
 */
 
@WebService(targetNamespace = "http://tempuri.org/", name = "WareServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface WareServiceSoap {

    @WebResult(name = "GetWareMcustDeliverResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetWareMcustDeliver", targetNamespace = "http://tempuri.org/", className = "com.pret.open.u9.warehouse.GetWareMcustDeliver")
    @ResponseWrapper(localName = "GetWareMcustDeliverResponse", targetNamespace = "http://tempuri.org/", className = "com.pret.open.u9.warehouse.GetWareMcustDeliverResponse")
    @WebMethod(operationName = "GetWareMcustDeliver", action = "http://tempuri.org/GetWareMcustDeliver")
    public ArrayOfWARE getWareMcustDeliver(
            @WebParam(name = "mcustno", targetNamespace = "http://tempuri.org/")
                    int mcustno,
            @WebParam(name = "DeliverCode", targetNamespace = "http://tempuri.org/")
                    int deliverCode
    );

    @WebResult(name = "GetWareDeliverStoreResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetWareDeliverStore", targetNamespace = "http://tempuri.org/", className = "com.pret.open.u9.warehouse.GetWareDeliverStore")
    @ResponseWrapper(localName = "GetWareDeliverStoreResponse", targetNamespace = "http://tempuri.org/", className = "com.pret.open.u9.warehouse.GetWareDeliverStoreResponse")
    @WebMethod(operationName = "GetWareDeliverStore", action = "http://tempuri.org/GetWareDeliverStore")
    public ArrayOfWARE getWareDeliverStore(
            @WebParam(name = "DeliverCode", targetNamespace = "http://tempuri.org/")
                    int deliverCode,
            @WebParam(name = "stroeid", targetNamespace = "http://tempuri.org/")
                    int stroeid
    );

    @WebResult(name = "GetWareMcustDeliverStoreResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetWareMcustDeliverStore", targetNamespace = "http://tempuri.org/", className = "com.pret.open.u9.warehouse.GetWareMcustDeliverStore")
    @ResponseWrapper(localName = "GetWareMcustDeliverStoreResponse", targetNamespace = "http://tempuri.org/", className = "com.pret.open.u9.warehouse.GetWareMcustDeliverStoreResponse")
    @WebMethod(operationName = "GetWareMcustDeliverStore", action = "http://tempuri.org/GetWareMcustDeliverStore")
    public ArrayOfWARE getWareMcustDeliverStore(
            @WebParam(name = "mcustno", targetNamespace = "http://tempuri.org/")
                    int mcustno,
            @WebParam(name = "DeliverCode", targetNamespace = "http://tempuri.org/")
                    int deliverCode,
            @WebParam(name = "stroeid", targetNamespace = "http://tempuri.org/")
                    int stroeid
    );

    @WebResult(name = "GetWareMcustDeliverFlagResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetWareMcustDeliverFlag", targetNamespace = "http://tempuri.org/", className = "com.pret.open.u9.warehouse.GetWareMcustDeliverFlag")
    @ResponseWrapper(localName = "GetWareMcustDeliverFlagResponse", targetNamespace = "http://tempuri.org/", className = "com.pret.open.u9.warehouse.GetWareMcustDeliverFlagResponse")
    @WebMethod(operationName = "GetWareMcustDeliverFlag", action = "http://tempuri.org/GetWareMcustDeliverFlag")
    public ArrayOfWARE getWareMcustDeliverFlag(
            @WebParam(name = "mcustno", targetNamespace = "http://tempuri.org/")
                    int mcustno,
            @WebParam(name = "DeliverCode", targetNamespace = "http://tempuri.org/")
                    int deliverCode,
            @WebParam(name = "flag", targetNamespace = "http://tempuri.org/")
                    int flag
    );

    @WebResult(name = "GetWareDeliverDistinctResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetWareDeliverDistinct", targetNamespace = "http://tempuri.org/", className = "com.pret.open.u9.warehouse.GetWareDeliverDistinct")
    @ResponseWrapper(localName = "GetWareDeliverDistinctResponse", targetNamespace = "http://tempuri.org/", className = "com.pret.open.u9.warehouse.GetWareDeliverDistinctResponse")
    @WebMethod(operationName = "GetWareDeliverDistinct", action = "http://tempuri.org/GetWareDeliverDistinct")
    public com.pret.open.u9.warehouse.ArrayOfWARE getWareDeliverDistinct();

    @WebResult(name = "GetMcustDistinctResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetMcustDistinct", targetNamespace = "http://tempuri.org/", className = "com.pret.open.u9.warehouse.GetMcustDistinct")
    @ResponseWrapper(localName = "GetMcustDistinctResponse", targetNamespace = "http://tempuri.org/", className = "com.pret.open.u9.warehouse.GetMcustDistinctResponse")
    @WebMethod(operationName = "GetMcustDistinct", action = "http://tempuri.org/GetMcustDistinct")
    public com.pret.open.u9.warehouse.ArrayOfWARE getMcustDistinct();

    @WebResult(name = "GetWareDeliverStoreFlagResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetWareDeliverStoreFlag", targetNamespace = "http://tempuri.org/", className = "com.pret.open.u9.warehouse.GetWareDeliverStoreFlag")
    @ResponseWrapper(localName = "GetWareDeliverStoreFlagResponse", targetNamespace = "http://tempuri.org/", className = "com.pret.open.u9.warehouse.GetWareDeliverStoreFlagResponse")
    @WebMethod(operationName = "GetWareDeliverStoreFlag", action = "http://tempuri.org/GetWareDeliverStoreFlag")
    public com.pret.open.u9.warehouse.ArrayOfWARE getWareDeliverStoreFlag(
            @WebParam(name = "DeliverCode", targetNamespace = "http://tempuri.org/")
                    int deliverCode,
            @WebParam(name = "stroeid", targetNamespace = "http://tempuri.org/")
                    int stroeid,
            @WebParam(name = "flag", targetNamespace = "http://tempuri.org/")
                    int flag
    );

    @WebResult(name = "GetWareDeliverDistinctByMcustResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetWareDeliverDistinctByMcust", targetNamespace = "http://tempuri.org/", className = "com.pret.open.u9.warehouse.GetWareDeliverDistinctByMcust")
    @ResponseWrapper(localName = "GetWareDeliverDistinctByMcustResponse", targetNamespace = "http://tempuri.org/", className = "com.pret.open.u9.warehouse.GetWareDeliverDistinctByMcustResponse")
    @WebMethod(operationName = "GetWareDeliverDistinctByMcust", action = "http://tempuri.org/GetWareDeliverDistinctByMcust")
    public com.pret.open.u9.warehouse.ArrayOfWARE getWareDeliverDistinctByMcust(
            @WebParam(name = "mcustno", targetNamespace = "http://tempuri.org/")
                    int mcustno
    );

    @WebResult(name = "GetWareDeliverStoreVRResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetWareDeliverStoreVR", targetNamespace = "http://tempuri.org/", className = "com.pret.open.u9.warehouse.GetWareDeliverStoreVR")
    @ResponseWrapper(localName = "GetWareDeliverStoreVRResponse", targetNamespace = "http://tempuri.org/", className = "com.pret.open.u9.warehouse.GetWareDeliverStoreVRResponse")
    @WebMethod(operationName = "GetWareDeliverStoreVR", action = "http://tempuri.org/GetWareDeliverStoreVR")
    public com.pret.open.u9.warehouse.ArrayOfWAREVR getWareDeliverStoreVR(
            @WebParam(name = "DeliverCode", targetNamespace = "http://tempuri.org/")
                    int deliverCode,
            @WebParam(name = "stroeid", targetNamespace = "http://tempuri.org/")
                    int stroeid
    );

    @WebResult(name = "GetWareDeliverResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetWareDeliver", targetNamespace = "http://tempuri.org/", className = "com.pret.open.u9.warehouse.GetWareDeliver")
    @ResponseWrapper(localName = "GetWareDeliverResponse", targetNamespace = "http://tempuri.org/", className = "com.pret.open.u9.warehouse.GetWareDeliverResponse")
    @WebMethod(operationName = "GetWareDeliver", action = "http://tempuri.org/GetWareDeliver")
    public com.pret.open.u9.warehouse.ArrayOfWARE getWareDeliver(
            @WebParam(name = "DeliverCode", targetNamespace = "http://tempuri.org/")
                    int deliverCode
    );

    @WebResult(name = "GetWareMcustResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetWareMcust", targetNamespace = "http://tempuri.org/", className = "com.pret.open.u9.warehouse.GetWareMcust")
    @ResponseWrapper(localName = "GetWareMcustResponse", targetNamespace = "http://tempuri.org/", className = "com.pret.open.u9.warehouse.GetWareMcustResponse")
    @WebMethod(operationName = "GetWareMcust", action = "http://tempuri.org/GetWareMcust")
    public ArrayOfWARE getWareMcust(
            @WebParam(name = "mcustno", targetNamespace = "http://tempuri.org/")
                    int mcustno
    );

    @WebResult(name = "GetWareResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetWare", targetNamespace = "http://tempuri.org/", className = "com.pret.open.u9.warehouse.GetWare")
    @ResponseWrapper(localName = "GetWareResponse", targetNamespace = "http://tempuri.org/", className = "com.pret.open.u9.warehouse.GetWareResponse")
    @WebMethod(operationName = "GetWare", action = "http://tempuri.org/GetWare")
    public ArrayOfWARE getWare();

    @WebResult(name = "GetWareMcustFlagResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetWareMcustFlag", targetNamespace = "http://tempuri.org/", className = "com.pret.open.u9.warehouse.GetWareMcustFlag")
    @ResponseWrapper(localName = "GetWareMcustFlagResponse", targetNamespace = "http://tempuri.org/", className = "com.pret.open.u9.warehouse.GetWareMcustFlagResponse")
    @WebMethod(operationName = "GetWareMcustFlag", action = "http://tempuri.org/GetWareMcustFlag")
    public ArrayOfWARE getWareMcustFlag(
            @WebParam(name = "mcustno", targetNamespace = "http://tempuri.org/")
                    int mcustno,
            @WebParam(name = "flag", targetNamespace = "http://tempuri.org/")
                    int flag
    );

    @WebResult(name = "GetWareFlagResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetWareFlag", targetNamespace = "http://tempuri.org/", className = "com.pret.open.u9.warehouse.GetWareFlag")
    @ResponseWrapper(localName = "GetWareFlagResponse", targetNamespace = "http://tempuri.org/", className = "com.pret.open.u9.warehouse.GetWareFlagResponse")
    @WebMethod(operationName = "GetWareFlag", action = "http://tempuri.org/GetWareFlag")
    public ArrayOfWARE getWareFlag(
            @WebParam(name = "flag", targetNamespace = "http://tempuri.org/")
                    int flag
    );

    @WebResult(name = "GetWareDeliverFlagResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetWareDeliverFlag", targetNamespace = "http://tempuri.org/", className = "com.pret.open.u9.warehouse.GetWareDeliverFlag")
    @ResponseWrapper(localName = "GetWareDeliverFlagResponse", targetNamespace = "http://tempuri.org/", className = "com.pret.open.u9.warehouse.GetWareDeliverFlagResponse")
    @WebMethod(operationName = "GetWareDeliverFlag", action = "http://tempuri.org/GetWareDeliverFlag")
    public ArrayOfWARE getWareDeliverFlag(
            @WebParam(name = "DeliverCode", targetNamespace = "http://tempuri.org/")
                    int deliverCode,
            @WebParam(name = "flag", targetNamespace = "http://tempuri.org/")
                    int flag
    );
}
