
package com.pret.open.u9.warehouse;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.2.4
 * Mon Nov 05 09:33:35 CST 2012
 * Generated source version: 2.2.4
 * 
 */

public final class WareServiceSoap_WareServiceSoap_Client {

    private static final QName SERVICE_NAME = new QName("http://tempuri.org/", "WareService");

    private WareServiceSoap_WareServiceSoap_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = WareService.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        WareService ss = new WareService(wsdlURL, SERVICE_NAME);
        WareServiceSoap port = ss.getWareServiceSoap();  
        
        {
        System.out.println("Invoking getWareMcustDeliver...");
        int _getWareMcustDeliver_mcustno = 0;
        int _getWareMcustDeliver_deliverCode = 0;
        ArrayOfWARE _getWareMcustDeliver__return = port.getWareMcustDeliver(_getWareMcustDeliver_mcustno, _getWareMcustDeliver_deliverCode);
        System.out.println("getWareMcustDeliver.result=" + _getWareMcustDeliver__return);


        }
        {
        System.out.println("Invoking getWareDeliverStore...");
        int _getWareDeliverStore_deliverCode = 0;
        int _getWareDeliverStore_stroeid = 0;
        ArrayOfWARE _getWareDeliverStore__return = port.getWareDeliverStore(_getWareDeliverStore_deliverCode, _getWareDeliverStore_stroeid);
        System.out.println("getWareDeliverStore.result=" + _getWareDeliverStore__return);


        }
        {
        System.out.println("Invoking getWareMcustDeliverStore...");
        int _getWareMcustDeliverStore_mcustno = 0;
        int _getWareMcustDeliverStore_deliverCode = 0;
        int _getWareMcustDeliverStore_stroeid = 0;
        ArrayOfWARE _getWareMcustDeliverStore__return = port.getWareMcustDeliverStore(_getWareMcustDeliverStore_mcustno, _getWareMcustDeliverStore_deliverCode, _getWareMcustDeliverStore_stroeid);
        System.out.println("getWareMcustDeliverStore.result=" + _getWareMcustDeliverStore__return);


        }
        {
        System.out.println("Invoking getWareMcustDeliverFlag...");
        int _getWareMcustDeliverFlag_mcustno = 0;
        int _getWareMcustDeliverFlag_deliverCode = 0;
        int _getWareMcustDeliverFlag_flag = 0;
        ArrayOfWARE _getWareMcustDeliverFlag__return = port.getWareMcustDeliverFlag(_getWareMcustDeliverFlag_mcustno, _getWareMcustDeliverFlag_deliverCode, _getWareMcustDeliverFlag_flag);
        System.out.println("getWareMcustDeliverFlag.result=" + _getWareMcustDeliverFlag__return);


        }
        {
        System.out.println("Invoking getWareDeliverDistinct...");
        ArrayOfWARE _getWareDeliverDistinct__return = port.getWareDeliverDistinct();
        System.out.println("getWareDeliverDistinct.result=" + _getWareDeliverDistinct__return);


        }
        {
        System.out.println("Invoking getMcustDistinct...");
        ArrayOfWARE _getMcustDistinct__return = port.getMcustDistinct();
        System.out.println("getMcustDistinct.result=" + _getMcustDistinct__return);


        }
        {
        System.out.println("Invoking getWareDeliverStoreFlag...");
        int _getWareDeliverStoreFlag_deliverCode = 0;
        int _getWareDeliverStoreFlag_stroeid = 0;
        int _getWareDeliverStoreFlag_flag = 0;
        ArrayOfWARE _getWareDeliverStoreFlag__return = port.getWareDeliverStoreFlag(_getWareDeliverStoreFlag_deliverCode, _getWareDeliverStoreFlag_stroeid, _getWareDeliverStoreFlag_flag);
        System.out.println("getWareDeliverStoreFlag.result=" + _getWareDeliverStoreFlag__return);


        }
        {
        System.out.println("Invoking getWareDeliverDistinctByMcust...");
        int _getWareDeliverDistinctByMcust_mcustno = 0;
        ArrayOfWARE _getWareDeliverDistinctByMcust__return = port.getWareDeliverDistinctByMcust(_getWareDeliverDistinctByMcust_mcustno);
        System.out.println("getWareDeliverDistinctByMcust.result=" + _getWareDeliverDistinctByMcust__return);


        }
        {
        System.out.println("Invoking getWareDeliverStoreVR...");
        int _getWareDeliverStoreVR_deliverCode = 0;
        int _getWareDeliverStoreVR_stroeid = 0;
        ArrayOfWAREVR _getWareDeliverStoreVR__return = port.getWareDeliverStoreVR(_getWareDeliverStoreVR_deliverCode, _getWareDeliverStoreVR_stroeid);
        System.out.println("getWareDeliverStoreVR.result=" + _getWareDeliverStoreVR__return);


        }
        {
        System.out.println("Invoking getWareDeliver...");
        int _getWareDeliver_deliverCode = 0;
        ArrayOfWARE _getWareDeliver__return = port.getWareDeliver(_getWareDeliver_deliverCode);
        System.out.println("getWareDeliver.result=" + _getWareDeliver__return);


        }
        {
        System.out.println("Invoking getWareMcust...");
        int _getWareMcust_mcustno = 0;
        ArrayOfWARE _getWareMcust__return = port.getWareMcust(_getWareMcust_mcustno);
        System.out.println("getWareMcust.result=" + _getWareMcust__return);


        }
        {
        System.out.println("Invoking getWare...");
        ArrayOfWARE _getWare__return = port.getWare();
        System.out.println("getWare.result=" + _getWare__return);


        }
        {
        System.out.println("Invoking getWareMcustFlag...");
        int _getWareMcustFlag_mcustno = 0;
        int _getWareMcustFlag_flag = 0;
        ArrayOfWARE _getWareMcustFlag__return = port.getWareMcustFlag(_getWareMcustFlag_mcustno, _getWareMcustFlag_flag);
        System.out.println("getWareMcustFlag.result=" + _getWareMcustFlag__return);


        }
        {
        System.out.println("Invoking getWareFlag...");
        int _getWareFlag_flag = 0;
        ArrayOfWARE _getWareFlag__return = port.getWareFlag(_getWareFlag_flag);
        System.out.println("getWareFlag.result=" + _getWareFlag__return);


        }
        {
        System.out.println("Invoking getWareDeliverFlag...");
        int _getWareDeliverFlag_deliverCode = 0;
        int _getWareDeliverFlag_flag = 0;
        ArrayOfWARE _getWareDeliverFlag__return = port.getWareDeliverFlag(_getWareDeliverFlag_deliverCode, _getWareDeliverFlag_flag);
        System.out.println("getWareDeliverFlag.result=" + _getWareDeliverFlag__return);


        }

        System.exit(0);
    }

}
