package com.pret.open.u9.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.4
 * Mon Dec 16 16:41:10 CST 2019
 * Generated source version: 2.2.4
 */

@WebService(targetNamespace = "http://tempuri.org/", name = "MBToERPServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface MBToERPServiceSoap {

    @WebMethod(operationName = "CreateDeliveryTask", action = "http://tempuri.org/CreateDeliveryTask")
    @RequestWrapper(localName = "CreateDeliveryTask", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CreateDeliveryTask")
    @ResponseWrapper(localName = "CreateDeliveryTaskResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CreateDeliveryTaskResponse")
    @WebResult(name = "CreateDeliveryTaskResult", targetNamespace = "http://tempuri.org/")
    public RetMsg createDeliveryTask(
            @WebParam(name = "DTDoc_LIST", targetNamespace = "http://tempuri.org/")
                    ArrayOfDTDoc dtDocLIST,
            @WebParam(name = "orgcode", targetNamespace = "http://tempuri.org/")
                    String orgcode,
            @WebParam(name = "usercode", targetNamespace = "http://tempuri.org/")
                    String usercode
    );

    @WebMethod(operationName = "UpdateDeliveryTaskFee", action = "http://tempuri.org/UpdateDeliveryTaskFee")
    @RequestWrapper(localName = "UpdateDeliveryTaskFee", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UpdateDeliveryTaskFee")
    @ResponseWrapper(localName = "UpdateDeliveryTaskFeeResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UpdateDeliveryTaskFeeResponse")
    @WebResult(name = "UpdateDeliveryTaskFeeResult", targetNamespace = "http://tempuri.org/")
    public RetMsg updateDeliveryTaskFee(
            @WebParam(name = "DTDoc_LIST", targetNamespace = "http://tempuri.org/")
                    ArrayOfFeeDoc dtDocLIST,
            @WebParam(name = "orgcode", targetNamespace = "http://tempuri.org/")
                    String orgcode,
            @WebParam(name = "usercode", targetNamespace = "http://tempuri.org/")
                    String usercode
    );
}
