package com.pret.service.handler;

import com.pret.api.vo.ReqBody;
import com.pret.vo.req.*;

import java.util.HashMap;
import java.util.Map;

import javax.persistence.*;
/** 
 * <p>Description: [pertmodel]</p>
 * Created on 2019年08月29日
 * @author  <a href="mailto: 1037216275@qq.com">wujinsong</a>
 * @version 1.0 
 * Copyright (c) 2019年 极客城堡
 */
public class InterfaceConfig  {
/* 接口处理器 */
public static final Map<String, String> JOP_HANDLER = new HashMap<String, String>();
/* 接口处理器 */
public static final Map<String, Class<? extends ReqBody>> JOP_VO = new HashMap<String, Class<? extends ReqBody>>();

	public static final String HPertAreaSave = "pertArea.save.do";
	public static final String HPertAreaDelete = "pertArea.delete.do";
	public static final String HPertAreaUpdate = "pertArea.update.do";
	public static final String HPertAreaQuery = "pertArea.query.get";
	public static final String HPertAreaDetail = "pertArea.detail.get";
	public static final String HPertCostPrescriptionSave = "pertCostPrescription.save.do";
	public static final String HPertCostPrescriptionDelete = "pertCostPrescription.delete.do";
	public static final String HPertCostPrescriptionUpdate = "pertCostPrescription.update.do";
	public static final String HPertCostPrescriptionQuery = "pertCostPrescription.query.get";
	public static final String HPertCostPrescriptionDetail = "pertCostPrescription.detail.get";
	public static final String HPertCustomerSave = "pertCustomer.save.do";
	public static final String HPertCustomerDelete = "pertCustomer.delete.do";
	public static final String HPertCustomerUpdate = "pertCustomer.update.do";
	public static final String HPertCustomerQuery = "pertCustomer.query.get";
	public static final String HPertCustomerDetail = "pertCustomer.detail.get";
	public static final String HPertCustomerUpdateSave = "pertCustomerUpdate.save.do";
	public static final String HPertCustomerUpdateDelete = "pertCustomerUpdate.delete.do";
	public static final String HPertCustomerUpdateUpdate = "pertCustomerUpdate.update.do";
	public static final String HPertCustomerUpdateQuery = "pertCustomerUpdate.query.get";
	public static final String HPertCustomerUpdateDetail = "pertCustomerUpdate.detail.get";
	public static final String HPertDeliveryOrderSave = "pertDeliveryOrder.save.do";
	public static final String HPertDeliveryOrderDelete = "pertDeliveryOrder.delete.do";
	public static final String HPertDeliveryOrderUpdate = "pertDeliveryOrder.update.do";
	public static final String HPertDeliveryOrderQuery = "pertDeliveryOrder.query.get";
	public static final String HPertDeliveryOrderDetail = "pertDeliveryOrder.detail.get";
	public static final String HPertDeliveryOrderItemSave = "pertDeliveryOrderItem.save.do";
	public static final String HPertDeliveryOrderItemDelete = "pertDeliveryOrderItem.delete.do";
	public static final String HPertDeliveryOrderItemUpdate = "pertDeliveryOrderItem.update.do";
	public static final String HPertDeliveryOrderItemQuery = "pertDeliveryOrderItem.query.get";
	public static final String HPertDeliveryOrderItemDetail = "pertDeliveryOrderItem.detail.get";
	public static final String HPertDriverSave = "pertDriver.save.do";
	public static final String HPertDriverDelete = "pertDriver.delete.do";
	public static final String HPertDriverUpdate = "pertDriver.update.do";
	public static final String HPertDriverQuery = "pertDriver.query.get";
	public static final String HPertDriverDetail = "pertDriver.detail.get";
	public static final String HPertExceptionSave = "pertException.save.do";
	public static final String HPertExceptionDelete = "pertException.delete.do";
	public static final String HPertExceptionUpdate = "pertException.update.do";
	public static final String HPertExceptionQuery = "pertException.query.get";
	public static final String HPertExceptionDetail = "pertException.detail.get";
	public static final String HPertGoodsSave = "pertGoods.save.do";
	public static final String HPertGoodsDelete = "pertGoods.delete.do";
	public static final String HPertGoodsUpdate = "pertGoods.update.do";
	public static final String HPertGoodsQuery = "pertGoods.query.get";
	public static final String HPertGoodsDetail = "pertGoods.detail.get";
	public static final String HPertOrderAdditionalCostsSave = "pertOrderAdditionalCosts.save.do";
	public static final String HPertOrderAdditionalCostsDelete = "pertOrderAdditionalCosts.delete.do";
	public static final String HPertOrderAdditionalCostsUpdate = "pertOrderAdditionalCosts.update.do";
	public static final String HPertOrderAdditionalCostsQuery = "pertOrderAdditionalCosts.query.get";
	public static final String HPertOrderAdditionalCostsDetail = "pertOrderAdditionalCosts.detail.get";
	public static final String HPertOverExpenditureAuditSave = "pertOverExpenditureAudit.save.do";
	public static final String HPertOverExpenditureAuditDelete = "pertOverExpenditureAudit.delete.do";
	public static final String HPertOverExpenditureAuditUpdate = "pertOverExpenditureAudit.update.do";
	public static final String HPertOverExpenditureAuditQuery = "pertOverExpenditureAudit.query.get";
	public static final String HPertOverExpenditureAuditDetail = "pertOverExpenditureAudit.detail.get";
	public static final String HPertPayableStatementSave = "pertPayableStatement.save.do";
	public static final String HPertPayableStatementDelete = "pertPayableStatement.delete.do";
	public static final String HPertPayableStatementUpdate = "pertPayableStatement.update.do";
	public static final String HPertPayableStatementQuery = "pertPayableStatement.query.get";
	public static final String HPertPayableStatementDetail = "pertPayableStatement.detail.get";
	public static final String HPertPickUpPlanSave = "pertPickUpPlan.save.do";
	public static final String HPertPickUpPlanDelete = "pertPickUpPlan.delete.do";
	public static final String HPertPickUpPlanUpdate = "pertPickUpPlan.update.do";
	public static final String HPertPickUpPlanQuery = "pertPickUpPlan.query.get";
	public static final String HPertPickUpPlanDetail = "pertPickUpPlan.detail.get";
	public static final String HPertPickUpPlanItemSave = "pertPickUpPlanItem.save.do";
	public static final String HPertPickUpPlanItemDelete = "pertPickUpPlanItem.delete.do";
	public static final String HPertPickUpPlanItemUpdate = "pertPickUpPlanItem.update.do";
	public static final String HPertPickUpPlanItemQuery = "pertPickUpPlanItem.query.get";
	public static final String HPertPickUpPlanItemDetail = "pertPickUpPlanItem.detail.get";
	public static final String HPertPriceSave = "pertPrice.save.do";
	public static final String HPertPriceDelete = "pertPrice.delete.do";
	public static final String HPertPriceUpdate = "pertPrice.update.do";
	public static final String HPertPriceQuery = "pertPrice.query.get";
	public static final String HPertPriceDetail = "pertPrice.detail.get";
	public static final String HPertPriceItemSave = "pertPriceItem.save.do";
	public static final String HPertPriceItemDelete = "pertPriceItem.delete.do";
	public static final String HPertPriceItemUpdate = "pertPriceItem.update.do";
	public static final String HPertPriceItemQuery = "pertPriceItem.query.get";
	public static final String HPertPriceItemDetail = "pertPriceItem.detail.get";
	public static final String HPertReconciliationExpensesSave = "pertReconciliationExpenses.save.do";
	public static final String HPertReconciliationExpensesDelete = "pertReconciliationExpenses.delete.do";
	public static final String HPertReconciliationExpensesUpdate = "pertReconciliationExpenses.update.do";
	public static final String HPertReconciliationExpensesQuery = "pertReconciliationExpenses.query.get";
	public static final String HPertReconciliationExpensesDetail = "pertReconciliationExpenses.detail.get";
	public static final String HPertServiceLineSave = "pertServiceLine.save.do";
	public static final String HPertServiceLineDelete = "pertServiceLine.delete.do";
	public static final String HPertServiceLineUpdate = "pertServiceLine.update.do";
	public static final String HPertServiceLineQuery = "pertServiceLine.query.get";
	public static final String HPertServiceLineDetail = "pertServiceLine.detail.get";
	public static final String HPertServiceLineItemSave = "pertServiceLineItem.save.do";
	public static final String HPertServiceLineItemDelete = "pertServiceLineItem.delete.do";
	public static final String HPertServiceLineItemUpdate = "pertServiceLineItem.update.do";
	public static final String HPertServiceLineItemQuery = "pertServiceLineItem.query.get";
	public static final String HPertServiceLineItemDetail = "pertServiceLineItem.detail.get";
	public static final String HPertSupplierSave = "pertSupplier.save.do";
	public static final String HPertSupplierDelete = "pertSupplier.delete.do";
	public static final String HPertSupplierUpdate = "pertSupplier.update.do";
	public static final String HPertSupplierQuery = "pertSupplier.query.get";
	public static final String HPertSupplierDetail = "pertSupplier.detail.get";
	public static final String HPertTransPlanSave = "pertTransPlan.save.do";
	public static final String HPertTransPlanDelete = "pertTransPlan.delete.do";
	public static final String HPertTransPlanUpdate = "pertTransPlan.update.do";
	public static final String HPertTransPlanQuery = "pertTransPlan.query.get";
	public static final String HPertTransPlanDetail = "pertTransPlan.detail.get";
	public static final String HPertTransPlanItemSave = "pertTransPlanItem.save.do";
	public static final String HPertTransPlanItemDelete = "pertTransPlanItem.delete.do";
	public static final String HPertTransPlanItemUpdate = "pertTransPlanItem.update.do";
	public static final String HPertTransPlanItemQuery = "pertTransPlanItem.query.get";
	public static final String HPertTransPlanItemDetail = "pertTransPlanItem.detail.get";
	public static final String HPertTransTrajectorySave = "pertTransTrajectory.save.do";
	public static final String HPertTransTrajectoryDelete = "pertTransTrajectory.delete.do";
	public static final String HPertTransTrajectoryUpdate = "pertTransTrajectory.update.do";
	public static final String HPertTransTrajectoryQuery = "pertTransTrajectory.query.get";
	public static final String HPertTransTrajectoryDetail = "pertTransTrajectory.detail.get";

static {
		JOP_HANDLER.put(HPertAreaSave, "HPertAreaSave");
		JOP_HANDLER.put(HPertAreaDelete, "HPertAreaDelete");
		JOP_HANDLER.put(HPertAreaUpdate, "HPertAreaUpdate");
		JOP_HANDLER.put(HPertAreaQuery, "HPertAreaQuery");
		JOP_HANDLER.put(HPertAreaDetail, "HPertAreaDetail");
		JOP_HANDLER.put(HPertCostPrescriptionSave, "HPertCostPrescriptionSave");
		JOP_HANDLER.put(HPertCostPrescriptionDelete, "HPertCostPrescriptionDelete");
		JOP_HANDLER.put(HPertCostPrescriptionUpdate, "HPertCostPrescriptionUpdate");
		JOP_HANDLER.put(HPertCostPrescriptionQuery, "HPertCostPrescriptionQuery");
		JOP_HANDLER.put(HPertCostPrescriptionDetail, "HPertCostPrescriptionDetail");
		JOP_HANDLER.put(HPertCustomerSave, "HPertCustomerSave");
		JOP_HANDLER.put(HPertCustomerDelete, "HPertCustomerDelete");
		JOP_HANDLER.put(HPertCustomerUpdate, "HPertCustomerUpdate");
		JOP_HANDLER.put(HPertCustomerQuery, "HPertCustomerQuery");
		JOP_HANDLER.put(HPertCustomerDetail, "HPertCustomerDetail");
		JOP_HANDLER.put(HPertCustomerUpdateSave, "HPertCustomerUpdateSave");
		JOP_HANDLER.put(HPertCustomerUpdateDelete, "HPertCustomerUpdateDelete");
		JOP_HANDLER.put(HPertCustomerUpdateUpdate, "HPertCustomerUpdateUpdate");
		JOP_HANDLER.put(HPertCustomerUpdateQuery, "HPertCustomerUpdateQuery");
		JOP_HANDLER.put(HPertCustomerUpdateDetail, "HPertCustomerUpdateDetail");
		JOP_HANDLER.put(HPertDeliveryOrderSave, "HPertDeliveryOrderSave");
		JOP_HANDLER.put(HPertDeliveryOrderDelete, "HPertDeliveryOrderDelete");
		JOP_HANDLER.put(HPertDeliveryOrderUpdate, "HPertDeliveryOrderUpdate");
		JOP_HANDLER.put(HPertDeliveryOrderQuery, "HPertDeliveryOrderQuery");
		JOP_HANDLER.put(HPertDeliveryOrderDetail, "HPertDeliveryOrderDetail");
		JOP_HANDLER.put(HPertDeliveryOrderItemSave, "HPertDeliveryOrderItemSave");
		JOP_HANDLER.put(HPertDeliveryOrderItemDelete, "HPertDeliveryOrderItemDelete");
		JOP_HANDLER.put(HPertDeliveryOrderItemUpdate, "HPertDeliveryOrderItemUpdate");
		JOP_HANDLER.put(HPertDeliveryOrderItemQuery, "HPertDeliveryOrderItemQuery");
		JOP_HANDLER.put(HPertDeliveryOrderItemDetail, "HPertDeliveryOrderItemDetail");
		JOP_HANDLER.put(HPertDriverSave, "HPertDriverSave");
		JOP_HANDLER.put(HPertDriverDelete, "HPertDriverDelete");
		JOP_HANDLER.put(HPertDriverUpdate, "HPertDriverUpdate");
		JOP_HANDLER.put(HPertDriverQuery, "HPertDriverQuery");
		JOP_HANDLER.put(HPertDriverDetail, "HPertDriverDetail");
		JOP_HANDLER.put(HPertExceptionSave, "HPertExceptionSave");
		JOP_HANDLER.put(HPertExceptionDelete, "HPertExceptionDelete");
		JOP_HANDLER.put(HPertExceptionUpdate, "HPertExceptionUpdate");
		JOP_HANDLER.put(HPertExceptionQuery, "HPertExceptionQuery");
		JOP_HANDLER.put(HPertExceptionDetail, "HPertExceptionDetail");
		JOP_HANDLER.put(HPertGoodsSave, "HPertGoodsSave");
		JOP_HANDLER.put(HPertGoodsDelete, "HPertGoodsDelete");
		JOP_HANDLER.put(HPertGoodsUpdate, "HPertGoodsUpdate");
		JOP_HANDLER.put(HPertGoodsQuery, "HPertGoodsQuery");
		JOP_HANDLER.put(HPertGoodsDetail, "HPertGoodsDetail");
		JOP_HANDLER.put(HPertOrderAdditionalCostsSave, "HPertOrderAdditionalCostsSave");
		JOP_HANDLER.put(HPertOrderAdditionalCostsDelete, "HPertOrderAdditionalCostsDelete");
		JOP_HANDLER.put(HPertOrderAdditionalCostsUpdate, "HPertOrderAdditionalCostsUpdate");
		JOP_HANDLER.put(HPertOrderAdditionalCostsQuery, "HPertOrderAdditionalCostsQuery");
		JOP_HANDLER.put(HPertOrderAdditionalCostsDetail, "HPertOrderAdditionalCostsDetail");
		JOP_HANDLER.put(HPertOverExpenditureAuditSave, "HPertOverExpenditureAuditSave");
		JOP_HANDLER.put(HPertOverExpenditureAuditDelete, "HPertOverExpenditureAuditDelete");
		JOP_HANDLER.put(HPertOverExpenditureAuditUpdate, "HPertOverExpenditureAuditUpdate");
		JOP_HANDLER.put(HPertOverExpenditureAuditQuery, "HPertOverExpenditureAuditQuery");
		JOP_HANDLER.put(HPertOverExpenditureAuditDetail, "HPertOverExpenditureAuditDetail");
		JOP_HANDLER.put(HPertPayableStatementSave, "HPertPayableStatementSave");
		JOP_HANDLER.put(HPertPayableStatementDelete, "HPertPayableStatementDelete");
		JOP_HANDLER.put(HPertPayableStatementUpdate, "HPertPayableStatementUpdate");
		JOP_HANDLER.put(HPertPayableStatementQuery, "HPertPayableStatementQuery");
		JOP_HANDLER.put(HPertPayableStatementDetail, "HPertPayableStatementDetail");
		JOP_HANDLER.put(HPertPickUpPlanSave, "HPertPickUpPlanSave");
		JOP_HANDLER.put(HPertPickUpPlanDelete, "HPertPickUpPlanDelete");
		JOP_HANDLER.put(HPertPickUpPlanUpdate, "HPertPickUpPlanUpdate");
		JOP_HANDLER.put(HPertPickUpPlanQuery, "HPertPickUpPlanQuery");
		JOP_HANDLER.put(HPertPickUpPlanDetail, "HPertPickUpPlanDetail");
		JOP_HANDLER.put(HPertPickUpPlanItemSave, "HPertPickUpPlanItemSave");
		JOP_HANDLER.put(HPertPickUpPlanItemDelete, "HPertPickUpPlanItemDelete");
		JOP_HANDLER.put(HPertPickUpPlanItemUpdate, "HPertPickUpPlanItemUpdate");
		JOP_HANDLER.put(HPertPickUpPlanItemQuery, "HPertPickUpPlanItemQuery");
		JOP_HANDLER.put(HPertPickUpPlanItemDetail, "HPertPickUpPlanItemDetail");
		JOP_HANDLER.put(HPertPriceSave, "HPertPriceSave");
		JOP_HANDLER.put(HPertPriceDelete, "HPertPriceDelete");
		JOP_HANDLER.put(HPertPriceUpdate, "HPertPriceUpdate");
		JOP_HANDLER.put(HPertPriceQuery, "HPertPriceQuery");
		JOP_HANDLER.put(HPertPriceDetail, "HPertPriceDetail");
		JOP_HANDLER.put(HPertPriceItemSave, "HPertPriceItemSave");
		JOP_HANDLER.put(HPertPriceItemDelete, "HPertPriceItemDelete");
		JOP_HANDLER.put(HPertPriceItemUpdate, "HPertPriceItemUpdate");
		JOP_HANDLER.put(HPertPriceItemQuery, "HPertPriceItemQuery");
		JOP_HANDLER.put(HPertPriceItemDetail, "HPertPriceItemDetail");
		JOP_HANDLER.put(HPertReconciliationExpensesSave, "HPertReconciliationExpensesSave");
		JOP_HANDLER.put(HPertReconciliationExpensesDelete, "HPertReconciliationExpensesDelete");
		JOP_HANDLER.put(HPertReconciliationExpensesUpdate, "HPertReconciliationExpensesUpdate");
		JOP_HANDLER.put(HPertReconciliationExpensesQuery, "HPertReconciliationExpensesQuery");
		JOP_HANDLER.put(HPertReconciliationExpensesDetail, "HPertReconciliationExpensesDetail");
		JOP_HANDLER.put(HPertServiceLineSave, "HPertServiceLineSave");
		JOP_HANDLER.put(HPertServiceLineDelete, "HPertServiceLineDelete");
		JOP_HANDLER.put(HPertServiceLineUpdate, "HPertServiceLineUpdate");
		JOP_HANDLER.put(HPertServiceLineQuery, "HPertServiceLineQuery");
		JOP_HANDLER.put(HPertServiceLineDetail, "HPertServiceLineDetail");
		JOP_HANDLER.put(HPertServiceLineItemSave, "HPertServiceLineItemSave");
		JOP_HANDLER.put(HPertServiceLineItemDelete, "HPertServiceLineItemDelete");
		JOP_HANDLER.put(HPertServiceLineItemUpdate, "HPertServiceLineItemUpdate");
		JOP_HANDLER.put(HPertServiceLineItemQuery, "HPertServiceLineItemQuery");
		JOP_HANDLER.put(HPertServiceLineItemDetail, "HPertServiceLineItemDetail");
		JOP_HANDLER.put(HPertSupplierSave, "HPertSupplierSave");
		JOP_HANDLER.put(HPertSupplierDelete, "HPertSupplierDelete");
		JOP_HANDLER.put(HPertSupplierUpdate, "HPertSupplierUpdate");
		JOP_HANDLER.put(HPertSupplierQuery, "HPertSupplierQuery");
		JOP_HANDLER.put(HPertSupplierDetail, "HPertSupplierDetail");
		JOP_HANDLER.put(HPertTransPlanSave, "HPertTransPlanSave");
		JOP_HANDLER.put(HPertTransPlanDelete, "HPertTransPlanDelete");
		JOP_HANDLER.put(HPertTransPlanUpdate, "HPertTransPlanUpdate");
		JOP_HANDLER.put(HPertTransPlanQuery, "HPertTransPlanQuery");
		JOP_HANDLER.put(HPertTransPlanDetail, "HPertTransPlanDetail");
		JOP_HANDLER.put(HPertTransPlanItemSave, "HPertTransPlanItemSave");
		JOP_HANDLER.put(HPertTransPlanItemDelete, "HPertTransPlanItemDelete");
		JOP_HANDLER.put(HPertTransPlanItemUpdate, "HPertTransPlanItemUpdate");
		JOP_HANDLER.put(HPertTransPlanItemQuery, "HPertTransPlanItemQuery");
		JOP_HANDLER.put(HPertTransPlanItemDetail, "HPertTransPlanItemDetail");
		JOP_HANDLER.put(HPertTransTrajectorySave, "HPertTransTrajectorySave");
		JOP_HANDLER.put(HPertTransTrajectoryDelete, "HPertTransTrajectoryDelete");
		JOP_HANDLER.put(HPertTransTrajectoryUpdate, "HPertTransTrajectoryUpdate");
		JOP_HANDLER.put(HPertTransTrajectoryQuery, "HPertTransTrajectoryQuery");
		JOP_HANDLER.put(HPertTransTrajectoryDetail, "HPertTransTrajectoryDetail");
}

static {
		JOP_VO.put(HPertAreaSave, PPertAreaSaveVo.class);
		JOP_VO.put(HPertAreaDelete, PPertAreaDeleteVo.class);
		JOP_VO.put(HPertAreaUpdate, PPertAreaUpdateVo.class);
		JOP_VO.put(HPertAreaQuery, PPertAreaQueryVo.class);
		JOP_VO.put(HPertAreaDetail, PPertAreaDetailVo.class);
		JOP_VO.put(HPertCostPrescriptionSave, PPertCostPrescriptionSaveVo.class);
		JOP_VO.put(HPertCostPrescriptionDelete, PPertCostPrescriptionDeleteVo.class);
		JOP_VO.put(HPertCostPrescriptionUpdate, PPertCostPrescriptionUpdateVo.class);
		JOP_VO.put(HPertCostPrescriptionQuery, PPertCostPrescriptionQueryVo.class);
		JOP_VO.put(HPertCostPrescriptionDetail, PPertCostPrescriptionDetailVo.class);
		JOP_VO.put(HPertCustomerSave, PPertCustomerSaveVo.class);
		JOP_VO.put(HPertCustomerDelete, PPertCustomerDeleteVo.class);
		JOP_VO.put(HPertCustomerUpdate, PPertCustomerUpdateVo.class);
		JOP_VO.put(HPertCustomerQuery, PPertCustomerQueryVo.class);
		JOP_VO.put(HPertCustomerDetail, PPertCustomerDetailVo.class);
		JOP_VO.put(HPertCustomerUpdateSave, PPertCustomerUpdateSaveVo.class);
		JOP_VO.put(HPertCustomerUpdateDelete, PPertCustomerUpdateDeleteVo.class);
		JOP_VO.put(HPertCustomerUpdateUpdate, PPertCustomerUpdateUpdateVo.class);
		JOP_VO.put(HPertCustomerUpdateQuery, PPertCustomerUpdateQueryVo.class);
		JOP_VO.put(HPertCustomerUpdateDetail, PPertCustomerUpdateDetailVo.class);
		JOP_VO.put(HPertDeliveryOrderSave, PPertDeliveryOrderSaveVo.class);
		JOP_VO.put(HPertDeliveryOrderDelete, PPertDeliveryOrderDeleteVo.class);
		JOP_VO.put(HPertDeliveryOrderUpdate, PPertDeliveryOrderUpdateVo.class);
		JOP_VO.put(HPertDeliveryOrderQuery, PPertDeliveryOrderQueryVo.class);
		JOP_VO.put(HPertDeliveryOrderDetail, PPertDeliveryOrderDetailVo.class);
		JOP_VO.put(HPertDeliveryOrderItemSave, PPertDeliveryOrderItemSaveVo.class);
		JOP_VO.put(HPertDeliveryOrderItemDelete, PPertDeliveryOrderItemDeleteVo.class);
		JOP_VO.put(HPertDeliveryOrderItemUpdate, PPertDeliveryOrderItemUpdateVo.class);
		JOP_VO.put(HPertDeliveryOrderItemQuery, PPertDeliveryOrderItemQueryVo.class);
		JOP_VO.put(HPertDeliveryOrderItemDetail, PPertDeliveryOrderItemDetailVo.class);
		JOP_VO.put(HPertDriverSave, PPertDriverSaveVo.class);
		JOP_VO.put(HPertDriverDelete, PPertDriverDeleteVo.class);
		JOP_VO.put(HPertDriverUpdate, PPertDriverUpdateVo.class);
		JOP_VO.put(HPertDriverQuery, PPertDriverQueryVo.class);
		JOP_VO.put(HPertDriverDetail, PPertDriverDetailVo.class);
		JOP_VO.put(HPertExceptionSave, PPertExceptionSaveVo.class);
		JOP_VO.put(HPertExceptionDelete, PPertExceptionDeleteVo.class);
		JOP_VO.put(HPertExceptionUpdate, PPertExceptionUpdateVo.class);
		JOP_VO.put(HPertExceptionQuery, PPertExceptionQueryVo.class);
		JOP_VO.put(HPertExceptionDetail, PPertExceptionDetailVo.class);
		JOP_VO.put(HPertGoodsSave, PPertGoodsSaveVo.class);
		JOP_VO.put(HPertGoodsDelete, PPertGoodsDeleteVo.class);
		JOP_VO.put(HPertGoodsUpdate, PPertGoodsUpdateVo.class);
		JOP_VO.put(HPertGoodsQuery, PPertGoodsQueryVo.class);
		JOP_VO.put(HPertGoodsDetail, PPertGoodsDetailVo.class);
		JOP_VO.put(HPertOrderAdditionalCostsSave, PPertOrderAdditionalCostsSaveVo.class);
		JOP_VO.put(HPertOrderAdditionalCostsDelete, PPertOrderAdditionalCostsDeleteVo.class);
		JOP_VO.put(HPertOrderAdditionalCostsUpdate, PPertOrderAdditionalCostsUpdateVo.class);
		JOP_VO.put(HPertOrderAdditionalCostsQuery, PPertOrderAdditionalCostsQueryVo.class);
		JOP_VO.put(HPertOrderAdditionalCostsDetail, PPertOrderAdditionalCostsDetailVo.class);
		JOP_VO.put(HPertOverExpenditureAuditSave, PPertOverExpenditureAuditSaveVo.class);
		JOP_VO.put(HPertOverExpenditureAuditDelete, PPertOverExpenditureAuditDeleteVo.class);
		JOP_VO.put(HPertOverExpenditureAuditUpdate, PPertOverExpenditureAuditUpdateVo.class);
		JOP_VO.put(HPertOverExpenditureAuditQuery, PPertOverExpenditureAuditQueryVo.class);
		JOP_VO.put(HPertOverExpenditureAuditDetail, PPertOverExpenditureAuditDetailVo.class);
		JOP_VO.put(HPertPayableStatementSave, PPertPayableStatementSaveVo.class);
		JOP_VO.put(HPertPayableStatementDelete, PPertPayableStatementDeleteVo.class);
		JOP_VO.put(HPertPayableStatementUpdate, PPertPayableStatementUpdateVo.class);
		JOP_VO.put(HPertPayableStatementQuery, PPertPayableStatementQueryVo.class);
		JOP_VO.put(HPertPayableStatementDetail, PPertPayableStatementDetailVo.class);
		JOP_VO.put(HPertPickUpPlanSave, PPertPickUpPlanSaveVo.class);
		JOP_VO.put(HPertPickUpPlanDelete, PPertPickUpPlanDeleteVo.class);
		JOP_VO.put(HPertPickUpPlanUpdate, PPertPickUpPlanUpdateVo.class);
		JOP_VO.put(HPertPickUpPlanQuery, PPertPickUpPlanQueryVo.class);
		JOP_VO.put(HPertPickUpPlanDetail, PPertPickUpPlanDetailVo.class);
		JOP_VO.put(HPertPickUpPlanItemSave, PPertPickUpPlanItemSaveVo.class);
		JOP_VO.put(HPertPickUpPlanItemDelete, PPertPickUpPlanItemDeleteVo.class);
		JOP_VO.put(HPertPickUpPlanItemUpdate, PPertPickUpPlanItemUpdateVo.class);
		JOP_VO.put(HPertPickUpPlanItemQuery, PPertPickUpPlanItemQueryVo.class);
		JOP_VO.put(HPertPickUpPlanItemDetail, PPertPickUpPlanItemDetailVo.class);
		JOP_VO.put(HPertPriceSave, PPertPriceSaveVo.class);
		JOP_VO.put(HPertPriceDelete, PPertPriceDeleteVo.class);
		JOP_VO.put(HPertPriceUpdate, PPertPriceUpdateVo.class);
		JOP_VO.put(HPertPriceQuery, PPertPriceQueryVo.class);
		JOP_VO.put(HPertPriceDetail, PPertPriceDetailVo.class);
		JOP_VO.put(HPertPriceItemSave, PPertPriceItemSaveVo.class);
		JOP_VO.put(HPertPriceItemDelete, PPertPriceItemDeleteVo.class);
		JOP_VO.put(HPertPriceItemUpdate, PPertPriceItemUpdateVo.class);
		JOP_VO.put(HPertPriceItemQuery, PPertPriceItemQueryVo.class);
		JOP_VO.put(HPertPriceItemDetail, PPertPriceItemDetailVo.class);
		JOP_VO.put(HPertReconciliationExpensesSave, PPertReconciliationExpensesSaveVo.class);
		JOP_VO.put(HPertReconciliationExpensesDelete, PPertReconciliationExpensesDeleteVo.class);
		JOP_VO.put(HPertReconciliationExpensesUpdate, PPertReconciliationExpensesUpdateVo.class);
		JOP_VO.put(HPertReconciliationExpensesQuery, PPertReconciliationExpensesQueryVo.class);
		JOP_VO.put(HPertReconciliationExpensesDetail, PPertReconciliationExpensesDetailVo.class);
		JOP_VO.put(HPertServiceLineSave, PPertServiceLineSaveVo.class);
		JOP_VO.put(HPertServiceLineDelete, PPertServiceLineDeleteVo.class);
		JOP_VO.put(HPertServiceLineUpdate, PPertServiceLineUpdateVo.class);
		JOP_VO.put(HPertServiceLineQuery, PPertServiceLineQueryVo.class);
		JOP_VO.put(HPertServiceLineDetail, PPertServiceLineDetailVo.class);
		JOP_VO.put(HPertServiceLineItemSave, PPertServiceLineItemSaveVo.class);
		JOP_VO.put(HPertServiceLineItemDelete, PPertServiceLineItemDeleteVo.class);
		JOP_VO.put(HPertServiceLineItemUpdate, PPertServiceLineItemUpdateVo.class);
		JOP_VO.put(HPertServiceLineItemQuery, PPertServiceLineItemQueryVo.class);
		JOP_VO.put(HPertServiceLineItemDetail, PPertServiceLineItemDetailVo.class);
		JOP_VO.put(HPertSupplierSave, PPertSupplierSaveVo.class);
		JOP_VO.put(HPertSupplierDelete, PPertSupplierDeleteVo.class);
		JOP_VO.put(HPertSupplierUpdate, PPertSupplierUpdateVo.class);
		JOP_VO.put(HPertSupplierQuery, PPertSupplierQueryVo.class);
		JOP_VO.put(HPertSupplierDetail, PPertSupplierDetailVo.class);
		JOP_VO.put(HPertTransPlanSave, PPertTransPlanSaveVo.class);
		JOP_VO.put(HPertTransPlanDelete, PPertTransPlanDeleteVo.class);
		JOP_VO.put(HPertTransPlanUpdate, PPertTransPlanUpdateVo.class);
		JOP_VO.put(HPertTransPlanQuery, PPertTransPlanQueryVo.class);
		JOP_VO.put(HPertTransPlanDetail, PPertTransPlanDetailVo.class);
		JOP_VO.put(HPertTransPlanItemSave, PPertTransPlanItemSaveVo.class);
		JOP_VO.put(HPertTransPlanItemDelete, PPertTransPlanItemDeleteVo.class);
		JOP_VO.put(HPertTransPlanItemUpdate, PPertTransPlanItemUpdateVo.class);
		JOP_VO.put(HPertTransPlanItemQuery, PPertTransPlanItemQueryVo.class);
		JOP_VO.put(HPertTransPlanItemDetail, PPertTransPlanItemDetailVo.class);
		JOP_VO.put(HPertTransTrajectorySave, PPertTransTrajectorySaveVo.class);
		JOP_VO.put(HPertTransTrajectoryDelete, PPertTransTrajectoryDeleteVo.class);
		JOP_VO.put(HPertTransTrajectoryUpdate, PPertTransTrajectoryUpdateVo.class);
		JOP_VO.put(HPertTransTrajectoryQuery, PPertTransTrajectoryQueryVo.class);
		JOP_VO.put(HPertTransTrajectoryDetail, PPertTransTrajectoryDetailVo.class);
}

}
